server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?serverTimezone=GMT%2B8&autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: qwer!234
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 50
      maxWait: 6000
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 30000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      validationQuery: SELECT 1 from dual
      connectionProperties: config.decrypt=false
  ##开发过程中建议关闭缓存
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8